# Generated by Django 4.0.5 on 2022-06-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('nama', models.CharField(max_length=100)),
                ('npm', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
